import type { FrequencyTier } from '../data/transitPlan'
import type { EdgeRoutingStyle } from './canvasGraph'
import type { TransitLanguage } from './gtfs'

export function isRtlLanguage(language: TransitLanguage) {
  return language !== 'English'
}

export function getDirection(language: TransitLanguage): 'ltr' | 'rtl' {
  return isRtlLanguage(language) ? 'rtl' : 'ltr'
}

export function getTextAlignment(language: TransitLanguage): 'left' | 'right' {
  return isRtlLanguage(language) ? 'right' : 'left'
}

type InterfaceCopy = {
  [key: string]: string | Record<FrequencyTier, string> | Record<EdgeRoutingStyle, string>
  edgeStyleOptions: Record<EdgeRoutingStyle, string>
  frequencyTierLabels: Record<FrequencyTier, string>
}

export const interfaceText = {
  English: {
    activeLanguage: 'Language',
    activeLegendBadge: 'Active',
    addPoi: 'Add POI',
    algorithms: 'Algorithms',
    architecture: 'Architecture',
    bundledFeedDescription: 'Built-in GTFS feed.',
    bundledFeedUnavailable: 'Built-in GTFS unavailable.',
    canvasBadgeExport: 'SVG export',
    canvasBadgeFeed: 'Real GTFS feed',
    canvasBadgeHubs: 'Transfer hubs',
    canvasBadgePoi: 'POI nodes',
    canvasRegionLabel: 'Transit map canvas',
    canvasRegionDescription: 'Editable transit map.',
    canvasTips: 'Canvas',
    customizeEdgeLabel: '{edge}',
    drawLinks: 'Drag to connect.',
    dragWithGrid: '20px grid.',
    edgeColor: 'Line Color',
    edgeColorSwatch: 'Use edge color {color}',
    edgeCustomization: 'Line Settings',
    edgeStrokeWidth: 'Stroke width',
    edgeStrokeWidthValue: '{count}px',
    edgeStyleOptions: {
      default: 'Curved / Flow',
      schematic: 'Octilinear (45°)',
      smoothstep: 'Rounded steps',
      straight: 'Straight lines',
    },
    editPoi: 'Edit selected POI.',
    export: 'Export',
    exportDescription: 'Temporarily fits the full graph into view before exporting the `.react-flow` canvas as SVG.',
    exportSvg: 'Export SVG',
    exportingSvg: 'Exporting SVG…',
    frequencyLegend: 'Frequency tiers',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'High frequency',
      LOW_FREQUENCY: 'Low frequency',
      MEDIUM_FREQUENCY: 'Medium frequency',
    },
    gtfsStationFallback: 'GTFS station',
    gtfsSource: 'GTFS source',
    gtfsAware: 'GTFS-aware',
    globalSetting: 'Global',
    headsign: 'Headsign',
    interactiveWorkspace: 'Canvas',
    installedPackages: 'Installed npm packages',
    language: 'Language',
    legendTitle: 'Legend',
    loadedFeedNotice: '{fileName} · {routes} routes · {trips} trips · {stops} stops · {hubs} hubs',
    loadFeedToBrowse: 'Load GTFS.',
    loadFeedToRestoreSharedMap: 'Shared map detected.',
    manualEdge: 'Manual POI connection',
    mapLineStyle: 'Map line style',
    mapLineStyleDescription: 'Style',
    noFeedLoaded: 'No feed loaded yet.',
    noRoutesMatch: 'No matches.',
    nodeLabelsBehavior: '{order} · {direction} · {alignment}',
    nodeLabelsDescription: 'RTL/LTR labels.',
    notProvided: 'Not provided',
    operatorLegend: 'Operator color',
    operatorColorsHeading: 'Operator colors',
    parsingGtfs: 'Loading GTFS…',
    phase: 'Phase 8',
    poiDescription: 'Edit POI.',
    poiNodes: 'POI nodes',
    readingArchive: 'Reading GTFS…',
    realDataOnly: 'Live MOT data',
    replaceGtfs: 'Replace GTFS ZIP',
    resultLabel: '{count} routes',
    routeMetadata: 'Route metadata',
    routeMode: 'Mode',
    routeOperator: 'Operator',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'React Flow canvas',
    rtlReady: 'RTL/LTR ready',
    selectEdgeBadge: 'No line selected',
    selectEdgeHint: 'Select a line.',
    searchAndSelection: 'Routes',
    searchPlaceholder: 'e.g. A1, Red Line, 480',
    searchRailLightBus: 'Search',
    selectPoiLabel: 'POI Label',
    shareCopied: 'Link copied.',
    shareCopyFailed: 'Copy failed.',
    shareDescription: 'Share URL.',
    singleStopHub: 'Single stop hub',
    shareMap: 'Share Map',
    stopsCount: '{count} stops',
    transferHubStops: '{count} linked stops',
    transitEdge: 'Transit line',
    trainNumberTemplate: 'Series',
    trainTemplateRendered: '{label}',
    tripsCount: '{count} trips',
    tripId: 'Trip ID',
    uploadGtfs: 'Upload GTFS ZIP',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} trips',
    liveRouteStyling: 'Live route styling',
    wheelchairAccessible: 'Wheelchair accessible',
    wheelchairInaccessible: 'Wheelchair inaccessible',
    wheelchairAccessibleStops: 'Wheelchair-accessible stops',
    wheelchairInaccessibleStops: 'Wheelchair-inaccessible stops',
  },
  'עברית': {
    activeLanguage: 'שפה',
    activeLegendBadge: 'פעיל',
    addPoi: 'הוספת POI',
    algorithms: 'אלגוריתמים',
    architecture: 'ארכיטקטורה',
    bundledFeedDescription: 'פיד GTFS מובנה.',
    bundledFeedUnavailable: 'פיד GTFS מובנה לא זמין.',
    canvasBadgeExport: 'ייצוא SVG',
    canvasBadgeFeed: 'פיד GTFS אמיתי',
    canvasBadgeHubs: 'מוקדי מעבר',
    canvasBadgePoi: 'נקודות עניין',
    canvasRegionLabel: 'קנבס מפת תחבורה',
    canvasRegionDescription: 'מפת תחבורה ניתנת לעריכה.',
    canvasTips: 'קנבס',
    customizeEdgeLabel: '{edge}',
    drawLinks: 'גרירה לחיבור.',
    dragWithGrid: 'רשת 20px.',
    edgeColor: 'צבע קו',
    edgeColorSwatch: 'בחירת צבע קו {color}',
    edgeCustomization: 'הגדרות קו',
    edgeStrokeWidth: 'עובי קו',
    edgeStrokeWidthValue: '{count}px',
    edgeStyleOptions: {
      default: 'מעוגל / Flow',
      schematic: 'אוקטילינארי (45°)',
      smoothstep: 'מדרגות מעוגלות',
      straight: 'קווים ישרים',
    },
    editPoi: 'עריכת POI נבחר.',
    export: 'ייצוא',
    exportDescription: 'הגרף כולו מותאם זמנית למסך לפני ייצוא קנבס `.react-flow` כ־SVG.',
    exportSvg: 'ייצוא SVG',
    exportingSvg: 'מייצא SVG…',
    frequencyLegend: 'רמות תדירות',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'תדירות גבוהה',
      LOW_FREQUENCY: 'תדירות נמוכה',
      MEDIUM_FREQUENCY: 'תדירות בינונית',
    },
    gtfsStationFallback: 'תחנת GTFS',
    gtfsSource: 'מקור GTFS',
    gtfsAware: 'מותאם ל‑GTFS',
    globalSetting: 'גלובלי',
    headsign: 'יעד',
    interactiveWorkspace: 'קנבס',
    installedPackages: 'חבילות npm מותקנות',
    language: 'שפה',
    legendTitle: 'מקרא',
    loadedFeedNotice: '{fileName} · ‏{routes} קווים · ‏{trips} נסיעות · ‏{stops} תחנות · ‏{hubs} מוקדים',
    loadFeedToBrowse: 'טענו GTFS.',
    loadFeedToRestoreSharedMap: 'זוהתה מפה משותפת.',
    manualEdge: 'חיבור POI ידני',
    mapLineStyle: 'סגנון קווי המפה',
    mapLineStyleDescription: 'סגנון',
    noFeedLoaded: 'עדיין לא נטען פיד.',
    noRoutesMatch: 'אין התאמות.',
    nodeLabelsBehavior: '{order} · {direction} · {alignment}',
    nodeLabelsDescription: 'תוויות RTL/LTR.',
    notProvided: 'לא סופק',
    operatorLegend: 'צבע מפעיל',
    operatorColorsHeading: 'צבעי מפעילים',
    parsingGtfs: 'טוען GTFS…',
    phase: 'שלב 8',
    poiDescription: 'עריכת POI.',
    poiNodes: 'נקודות עניין',
    readingArchive: 'קורא GTFS…',
    realDataOnly: 'נתוני משרד התחבורה',
    replaceGtfs: 'החלפת קובץ GTFS',
    resultLabel: '{count} קווים',
    routeMetadata: 'פרטי קו',
    routeMode: 'סוג',
    routeOperator: 'מפעיל',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'קנבס React Flow',
    rtlReady: 'מוכן ל‑RTL/LTR',
    selectEdgeBadge: 'לא נבחר קו',
    selectEdgeHint: 'בחרו קו.',
    searchAndSelection: 'קווים',
    searchPlaceholder: 'למשל A1, Red Line, 480',
    searchRailLightBus: 'חיפוש',
    selectPoiLabel: 'תווית POI',
    shareCopied: 'הקישור הועתק.',
    shareCopyFailed: 'ההעתקה נכשלה.',
    shareDescription: 'קישור שיתוף.',
    singleStopHub: 'מוקד של תחנה אחת',
    shareMap: 'שיתוף מפה',
    stopsCount: '{count} תחנות',
    transferHubStops: '{count} תחנות מקושרות',
    transitEdge: 'קו תחבורה',
    trainNumberTemplate: 'סדרה',
    trainTemplateRendered: '{label}',
    tripsCount: '{count} נסיעות',
    tripId: 'מזהה נסיעה',
    uploadGtfs: 'העלאת קובץ GTFS',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} נסיעות',
    liveRouteStyling: 'עיצוב קו חי',
    wheelchairAccessible: 'גישה לכיסא גלגלים',
    wheelchairInaccessible: 'ללא גישה לכיסא גלגלים',
    wheelchairAccessibleStops: 'תחנות נגישות לכיסא גלגלים',
    wheelchairInaccessibleStops: 'תחנות לא נגישות לכיסא גלגלים',
  },
  'العربية': {
    activeLanguage: 'اللغة',
    activeLegendBadge: 'نشط',
    addPoi: 'إضافة POI',
    algorithms: 'الخوارزميات',
    architecture: 'البنية',
    bundledFeedDescription: 'تغذية GTFS مدمجة.',
    bundledFeedUnavailable: 'تغذية GTFS المدمجة غير متاحة.',
    canvasBadgeExport: 'تصدير SVG',
    canvasBadgeFeed: 'تغذية GTFS حقيقية',
    canvasBadgeHubs: 'مراكز التحويل',
    canvasBadgePoi: 'نقاط الاهتمام',
    canvasRegionLabel: 'لوحة خريطة النقل',
    canvasRegionDescription: 'خريطة نقل قابلة للتحرير.',
    canvasTips: 'اللوحة',
    customizeEdgeLabel: '{edge}',
    drawLinks: 'اسحب للربط.',
    dragWithGrid: 'شبكة 20px.',
    edgeColor: 'لون الخط',
    edgeColorSwatch: 'استخدم لون الخط {color}',
    edgeCustomization: 'إعدادات الخط',
    edgeStrokeWidth: 'سماكة الخط',
    edgeStrokeWidthValue: '{count}px',
    edgeStyleOptions: {
      default: 'منحني / Flow',
      schematic: 'ثماني الاتجاهات (45°)',
      smoothstep: 'خطوات مستديرة',
      straight: 'خطوط مستقيمة',
    },
    editPoi: 'عدّل POI المحدد.',
    export: 'تصدير',
    exportDescription: 'يتم احتواء المخطط كاملًا مؤقتًا قبل تصدير لوحة `.react-flow` كملف SVG.',
    exportSvg: 'تصدير SVG',
    exportingSvg: 'جارٍ تصدير SVG…',
    frequencyLegend: 'مستويات التردد',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'تردد مرتفع',
      LOW_FREQUENCY: 'تردد منخفض',
      MEDIUM_FREQUENCY: 'تردد متوسط',
    },
    gtfsStationFallback: 'محطة GTFS',
    gtfsSource: 'مصدر GTFS',
    gtfsAware: 'مدعوم بـ GTFS',
    globalSetting: 'عام',
    headsign: 'الوجهة',
    interactiveWorkspace: 'اللوحة',
    installedPackages: 'حزم npm المثبتة',
    language: 'اللغة',
    legendTitle: 'المفتاح',
    loadedFeedNotice: '{fileName} · {routes} خطوط · {trips} رحلات · {stops} محطات · {hubs} مراكز',
    loadFeedToBrowse: 'حمّل GTFS.',
    loadFeedToRestoreSharedMap: 'تم اكتشاف خريطة مشتركة.',
    manualEdge: 'وصلة POI يدوية',
    mapLineStyle: 'نمط خطوط الخريطة',
    mapLineStyleDescription: 'النمط',
    noFeedLoaded: 'لم يتم تحميل أي تغذية بعد.',
    noRoutesMatch: 'لا توجد نتائج.',
    nodeLabelsBehavior: '{order} · {direction} · {alignment}',
    nodeLabelsDescription: 'تسميات RTL/LTR.',
    notProvided: 'غير متوفر',
    operatorLegend: 'لون المشغّل',
    operatorColorsHeading: 'ألوان المشغّلين',
    parsingGtfs: 'جارٍ تحميل GTFS…',
    phase: 'المرحلة 8',
    poiDescription: 'عدّل POI.',
    poiNodes: 'نقاط الاهتمام',
    readingArchive: 'جارٍ قراءة GTFS…',
    realDataOnly: 'بيانات الوزارة المباشرة',
    replaceGtfs: 'استبدال ملف GTFS',
    resultLabel: '{count} خطوط',
    routeMetadata: 'بيانات الخط',
    routeMode: 'النوع',
    routeOperator: 'المشغّل',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'لوحة React Flow',
    rtlReady: 'جاهز لـ RTL/LTR',
    selectEdgeBadge: 'لا يوجد خط محدد',
    selectEdgeHint: 'حدّد خطًا.',
    searchAndSelection: 'الخطوط',
    searchPlaceholder: 'مثال: A1 أو Red Line أو 480',
    searchRailLightBus: 'بحث',
    selectPoiLabel: 'تسمية POI',
    shareCopied: 'تم نسخ الرابط.',
    shareCopyFailed: 'فشل النسخ.',
    shareDescription: 'رابط مشاركة.',
    singleStopHub: 'مركز لمحطة واحدة',
    shareMap: 'مشاركة الخريطة',
    stopsCount: '{count} محطات',
    transferHubStops: '{count} محطات مترابطة',
    transitEdge: 'خط نقل',
    trainNumberTemplate: 'السلسلة',
    trainTemplateRendered: '{label}',
    tripsCount: '{count} رحلة',
    tripId: 'معرّف الرحلة',
    uploadGtfs: 'تحميل ملف GTFS',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} رحلة',
    liveRouteStyling: 'تصميم الخط المباشر',
    wheelchairAccessible: 'إمكانية وصول بالكراسي المتحركة',
    wheelchairInaccessible: 'غير متاح للكراسي المتحركة',
    wheelchairAccessibleStops: 'محطات متاحة للكراسي المتحركة',
    wheelchairInaccessibleStops: 'محطات غير متاحة للكراسي المتحركة',
  },
} satisfies Record<TransitLanguage, InterfaceCopy>
