import type { TransitLanguage } from './gtfs'
import type { FrequencyTier } from '../data/transitPlan'

export function isRtlLanguage(language: TransitLanguage) {
  return language !== 'English'
}

export function getDirection(language: TransitLanguage): 'ltr' | 'rtl' {
  return isRtlLanguage(language) ? 'rtl' : 'ltr'
}

export function getTextAlignment(language: TransitLanguage): 'left' | 'right' {
  return isRtlLanguage(language) ? 'right' : 'left'
}

type InterfaceCopy = {
  [key: string]: string | Record<FrequencyTier, string>
  frequencyTierLabels: Record<FrequencyTier, string>
}

export const interfaceText = {
  English: {
    activeLanguage: 'Active language',
    activeLegendBadge: 'Active',
    addPoi: 'Add POI to canvas center',
    algorithms: 'Algorithms',
    architecture: 'Architecture',
    canvasBadgeExport: 'SVG export',
    canvasBadgeFeed: 'Real GTFS feed',
    canvasBadgeHubs: 'Transfer hubs',
    canvasBadgePoi: 'POI nodes',
    canvasRegionLabel: 'Interactive transit map canvas',
    canvasRegionDescription:
      'Use the interactive graph to inspect GTFS station and transfer hub nodes, add POI nodes from the sidebar, draw pointer-based octilinear manual connections, and export or share the full React Flow canvas.',
    canvasTips: 'Canvas tips',
    drawLinks: 'Draw new links by dragging between POI and transit handles.',
    dragWithGrid: 'Drag GTFS stations, transfer hubs, or POI nodes with 20px grid snapping.',
    editPoi: 'Select a POI node, then edit its label from the sidebar.',
    export: 'Export',
    exportDescription: 'Temporarily fits the full graph into view before exporting the `.react-flow` canvas as SVG.',
    exportSvg: 'Export SVG',
    exportingSvg: 'Exporting SVG…',
    frequencyLegend: 'Frequency tiers',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'High frequency',
      LOW_FREQUENCY: 'Low frequency',
      MEDIUM_FREQUENCY: 'Medium frequency',
    },
    gtfsStationFallback: 'GTFS station',
    gtfsSource: 'GTFS source',
    gtfsAware: 'GTFS-aware',
    headsign: 'Headsign',
    interactiveWorkspace: 'Interactive schematic workspace',
    installedPackages: 'Installed npm packages',
    language: 'Language',
    legendTitle: 'Legend',
    loadedFeedNotice: 'Loaded {fileName} · {routes} routes · {trips} trips · {stops} stops · {hubs} hubs',
    loadFeedToBrowse: 'Load a feed to browse routes.',
    loadFeedToRestoreSharedMap: 'Shared map found. Upload the matching GTFS zip to restore the saved layout.',
    noFeedLoaded: 'No feed loaded yet.',
    noRoutesMatch: 'No routes match the current search.',
    nodeLabelsDescription: 'Canvas labels switch between RTL and LTR reading order without resetting node positions.',
    notProvided: 'Not provided',
    operatorLegend: 'Operator color',
    operatorColorsHeading: 'Operator colors',
    parsingGtfs: 'Parsing GTFS archive…',
    phase: 'Phase 7',
    poiDescription: 'Create a POI, click it on the canvas, then edit its label here.',
    poiNodes: 'POI nodes',
    readingArchive: 'Reading routes, trips, stop_times, stops, and translations from the uploaded archive.',
    realDataOnly: 'Real data only',
    resultLabel: '{count} routes shown from the loaded GTFS feed',
    routeMetadata: 'Route metadata',
    routeMode: 'Mode',
    routeOperator: 'Operator',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'React Flow canvas',
    rtlReady: 'RTL/LTR ready',
    searchAndSelection: 'Search & selection',
    searchPlaceholder: 'e.g. A1, Red Line, 480',
    searchRailLightBus: 'Search rail, light rail, or bus lines',
    selectPoiLabel: 'Selected POI label',
    shareCopied: 'Share link copied to clipboard.',
    shareCopyFailed: 'Unable to copy the share link. Copy it from the address bar instead.',
    shareDescription: 'Creates a compressed GitHub Pages-safe URL with the selected lines, POIs, and node positions.',
    singleStopHub: 'Single stop hub',
    shareMap: 'Share Map',
    stopsCount: '{count} stops',
    transferHubStops: '{count} linked stops',
    trainNumberTemplate: 'Train number template',
    trainTemplateRendered: 'Rendered on the longest octilinear segment: {label}',
    tripsCount: '{count} trips',
    tripId: 'Trip ID',
    uploadGtfs: 'Upload an official Israel MOT GTFS zip archive',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} trips in the loaded feed',
    liveRouteStyling: 'Live route styling',
    wheelchairAccessible: 'Wheelchair accessible',
    wheelchairInaccessible: 'Wheelchair inaccessible',
    wheelchairAccessibleStops: 'Wheelchair-accessible stops',
    wheelchairInaccessibleStops: 'Wheelchair-inaccessible stops',
  },
  'עברית': {
    activeLanguage: 'שפה פעילה',
    activeLegendBadge: 'פעיל',
    addPoi: 'הוספת נקודת עניין למרכז הקנבס',
    algorithms: 'אלגוריתמים',
    architecture: 'ארכיטקטורה',
    canvasBadgeExport: 'ייצוא SVG',
    canvasBadgeFeed: 'פיד GTFS אמיתי',
    canvasBadgeHubs: 'מוקדי מעבר',
    canvasBadgePoi: 'נקודות עניין',
    canvasRegionLabel: 'קנבס מפת תחבורה אינטראקטיבי',
    canvasRegionDescription:
      'השתמשו בגרף האינטראקטיבי כדי לבדוק תחנות GTFS ומוקדי מעבר, להוסיף נקודות עניין מהסרגל הצדדי, לצייר חיבורים אוקטילינאריים באמצעות העכבר, ולייצא או לשתף את קנבס React Flow המלא.',
    canvasTips: 'טיפים לקנבס',
    drawLinks: 'צרו חיבורים חדשים על ידי גרירה בין ידיות של נקודות עניין ותחנות.',
    dragWithGrid: 'גררו תחנות GTFS, מוקדי מעבר או נקודות עניין עם הצמדה לרשת של 20 פיקסלים.',
    editPoi: 'בחרו נקודת עניין ואז ערכו את התווית שלה מהסרגל הצדדי.',
    export: 'ייצוא',
    exportDescription: 'הגרף כולו מותאם זמנית למסך לפני ייצוא קנבס `.react-flow` כ־SVG.',
    exportSvg: 'ייצוא SVG',
    exportingSvg: 'מייצא SVG…',
    frequencyLegend: 'רמות תדירות',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'תדירות גבוהה',
      LOW_FREQUENCY: 'תדירות נמוכה',
      MEDIUM_FREQUENCY: 'תדירות בינונית',
    },
    gtfsStationFallback: 'תחנת GTFS',
    gtfsSource: 'מקור GTFS',
    gtfsAware: 'מותאם ל‑GTFS',
    headsign: 'יעד',
    interactiveWorkspace: 'סביבת עבודה סכמטית אינטראקטיבית',
    installedPackages: 'חבילות npm מותקנות',
    language: 'שפה',
    legendTitle: 'מקרא',
    loadedFeedNotice: 'נטען {fileName} · ‏{routes} קווים · ‏{trips} נסיעות · ‏{stops} תחנות · ‏{hubs} מוקדים',
    loadFeedToBrowse: 'טענו פיד כדי לעיין בקווים.',
    loadFeedToRestoreSharedMap: 'נמצאה מפה משותפת. העלו את קובץ ה‑GTFS המתאים כדי לשחזר את הפריסה השמורה.',
    noFeedLoaded: 'עדיין לא נטען פיד.',
    noRoutesMatch: 'אין קווים התואמים לחיפוש הנוכחי.',
    nodeLabelsDescription: 'תוויות הקנבס עוברות בין RTL ל‑LTR בלי לאפס את מיקומי הצמתים.',
    notProvided: 'לא סופק',
    operatorLegend: 'צבע מפעיל',
    operatorColorsHeading: 'צבעי מפעילים',
    parsingGtfs: 'מנתח ארכיון GTFS…',
    phase: 'שלב 7',
    poiDescription: 'צרו נקודת עניין, לחצו עליה בקנבס ואז ערכו את התווית כאן.',
    poiNodes: 'נקודות עניין',
    readingArchive: 'קורא routes, trips, stop_times, stops ו‑translations מתוך הארכיון שהועלה.',
    realDataOnly: 'נתונים אמיתיים בלבד',
    resultLabel: '{count} קווים מוצגים מתוך פיד ה‑GTFS שנטען',
    routeMetadata: 'פרטי קו',
    routeMode: 'סוג',
    routeOperator: 'מפעיל',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'קנבס React Flow',
    rtlReady: 'מוכן ל‑RTL/LTR',
    searchAndSelection: 'חיפוש ובחירה',
    searchPlaceholder: 'למשל A1, Red Line, 480',
    searchRailLightBus: 'חפשו קווי רכבת, רכבת קלה או אוטובוס',
    selectPoiLabel: 'תווית נקודת העניין שנבחרה',
    shareCopied: 'קישור השיתוף הועתק ללוח.',
    shareCopyFailed: 'לא ניתן להעתיק את קישור השיתוף. העתיקו אותו משורת הכתובת.',
    shareDescription: 'יוצר כתובת דחוסה ותואמת GitHub Pages עם הקווים, נקודות העניין ומיקומי הצמתים.',
    singleStopHub: 'מוקד של תחנה אחת',
    shareMap: 'שיתוף מפה',
    stopsCount: '{count} תחנות',
    transferHubStops: '{count} תחנות מקושרות',
    trainNumberTemplate: 'תבנית מספר רכבת',
    trainTemplateRendered: 'מוצג על המקטע האוקטילינארי הארוך ביותר: {label}',
    tripsCount: '{count} נסיעות',
    tripId: 'מזהה נסיעה',
    uploadGtfs: 'העלו קובץ ZIP רשמי של GTFS ממשרד התחבורה',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} נסיעות בפיד שנטען',
    liveRouteStyling: 'עיצוב קו חי',
    wheelchairAccessible: 'גישה לכיסא גלגלים',
    wheelchairInaccessible: 'ללא גישה לכיסא גלגלים',
    wheelchairAccessibleStops: 'תחנות נגישות לכיסא גלגלים',
    wheelchairInaccessibleStops: 'תחנות לא נגישות לכיסא גלגלים',
  },
  'العربية': {
    activeLanguage: 'اللغة النشطة',
    activeLegendBadge: 'نشط',
    addPoi: 'إضافة نقطة اهتمام إلى وسط اللوحة',
    algorithms: 'الخوارزميات',
    architecture: 'البنية',
    canvasBadgeExport: 'تصدير SVG',
    canvasBadgeFeed: 'تغذية GTFS حقيقية',
    canvasBadgeHubs: 'مراكز التحويل',
    canvasBadgePoi: 'نقاط الاهتمام',
    canvasRegionLabel: 'لوحة خريطة نقل تفاعلية',
    canvasRegionDescription:
      'استخدم المخطط التفاعلي لفحص محطات GTFS وعُقد التحويل، وإضافة نقاط اهتمام من الشريط الجانبي، ورسم وصلات ثمانية الاتجاهات بالمؤشر، ثم تصدير أو مشاركة لوحة React Flow كاملة.',
    canvasTips: 'نصائح اللوحة',
    drawLinks: 'ارسم وصلات جديدة عبر السحب بين مقابض نقاط الاهتمام والمحطات.',
    dragWithGrid: 'اسحب محطات GTFS وعُقد التحويل أو نقاط الاهتمام مع الالتقاط إلى شبكة 20 بكسل.',
    editPoi: 'حدّد نقطة اهتمام ثم عدّل تسميتها من الشريط الجانبي.',
    export: 'تصدير',
    exportDescription: 'يتم احتواء المخطط كاملًا مؤقتًا قبل تصدير لوحة `.react-flow` كملف SVG.',
    exportSvg: 'تصدير SVG',
    exportingSvg: 'جارٍ تصدير SVG…',
    frequencyLegend: 'مستويات التردد',
    frequencyTierLabels: {
      HIGH_FREQUENCY: 'تردد مرتفع',
      LOW_FREQUENCY: 'تردد منخفض',
      MEDIUM_FREQUENCY: 'تردد متوسط',
    },
    gtfsStationFallback: 'محطة GTFS',
    gtfsSource: 'مصدر GTFS',
    gtfsAware: 'مدعوم بـ GTFS',
    headsign: 'الوجهة',
    interactiveWorkspace: 'مساحة عمل تخطيطية تفاعلية',
    installedPackages: 'حزم npm المثبتة',
    language: 'اللغة',
    legendTitle: 'المفتاح',
    loadedFeedNotice: 'تم تحميل {fileName} · {routes} خطوط · {trips} رحلات · {stops} محطات · {hubs} مراكز',
    loadFeedToBrowse: 'حمّل تغذية للتصفح بين الخطوط.',
    loadFeedToRestoreSharedMap: 'تم العثور على خريطة مشتركة. حمّل ملف GTFS المطابق لاستعادة التخطيط المحفوظ.',
    noFeedLoaded: 'لم يتم تحميل أي تغذية بعد.',
    noRoutesMatch: 'لا توجد خطوط تطابق البحث الحالي.',
    nodeLabelsDescription: 'تبدّل تسميات اللوحة بين اتجاهي RTL وLTR بدون إعادة تعيين مواقع العقد.',
    notProvided: 'غير متوفر',
    operatorLegend: 'لون المشغّل',
    operatorColorsHeading: 'ألوان المشغّلين',
    parsingGtfs: 'جارٍ تحليل أرشيف GTFS…',
    phase: 'المرحلة 7',
    poiDescription: 'أنشئ نقطة اهتمام، ثم اضغط عليها في اللوحة وعدّل تسميتها هنا.',
    poiNodes: 'نقاط الاهتمام',
    readingArchive: 'تتم قراءة routes وtrips وstop_times وstops وtranslations من الأرشيف المرفوع.',
    realDataOnly: 'بيانات حقيقية فقط',
    resultLabel: 'يتم عرض {count} خطوط من تغذية GTFS المحمّلة',
    routeMetadata: 'بيانات الخط',
    routeMode: 'النوع',
    routeOperator: 'المشغّل',
    reactFlowBadge: 'React Flow',
    reactFlowCanvas: 'لوحة React Flow',
    rtlReady: 'جاهز لـ RTL/LTR',
    searchAndSelection: 'البحث والاختيار',
    searchPlaceholder: 'مثال: A1 أو Red Line أو 480',
    searchRailLightBus: 'ابحث عن خطوط القطار أو القطار الخفيف أو الحافلات',
    selectPoiLabel: 'تسمية نقطة الاهتمام المحددة',
    shareCopied: 'تم نسخ رابط المشاركة إلى الحافظة.',
    shareCopyFailed: 'تعذر نسخ رابط المشاركة. انسخه من شريط العنوان بدلًا من ذلك.',
    shareDescription: 'ينشئ رابطًا مضغوطًا وآمنًا مع GitHub Pages يتضمن الخطوط ونقاط الاهتمام ومواقع العقد.',
    singleStopHub: 'مركز لمحطة واحدة',
    shareMap: 'مشاركة الخريطة',
    stopsCount: '{count} محطات',
    transferHubStops: '{count} محطات مترابطة',
    trainNumberTemplate: 'قالب رقم القطار',
    trainTemplateRendered: 'يُعرض على أطول مقطع ثماني الاتجاهات: {label}',
    tripsCount: '{count} رحلة',
    tripId: 'معرّف الرحلة',
    uploadGtfs: 'حمّل ملف GTFS رسمي بصيغة ZIP من وزارة المواصلات',
    urlBadge: 'URL',
    vectorSvg: 'SVG',
    visibleRouteTrips: '{count} رحلة في التغذية المحمّلة',
    liveRouteStyling: 'تصميم الخط المباشر',
    wheelchairAccessible: 'إمكانية وصول بالكراسي المتحركة',
    wheelchairInaccessible: 'غير متاح للكراسي المتحركة',
    wheelchairAccessibleStops: 'محطات متاحة للكراسي المتحركة',
    wheelchairInaccessibleStops: 'محطات غير متاحة للكراسي المتحركة',
  },
} satisfies Record<TransitLanguage, InterfaceCopy>
