import type { TransitLanguage } from './gtfs'

export function isRtlLanguage(language: TransitLanguage) {
  return language !== 'English'
}

export function getDirection(language: TransitLanguage): 'ltr' | 'rtl' {
  return isRtlLanguage(language) ? 'rtl' : 'ltr'
}

export function getTextAlignment(language: TransitLanguage): 'left' | 'right' {
  return isRtlLanguage(language) ? 'right' : 'left'
}

export const interfaceText = {
  English: {
    activeLanguage: 'Active language',
    addPoi: 'Add POI to canvas center',
    architecture: 'Architecture',
    canvasRegionDescription:
      'Use the interactive graph to inspect GTFS station and transfer hub nodes, add POI nodes from the sidebar, draw pointer-based octilinear manual connections, and export or share the full React Flow canvas.',
    canvasTips: 'Canvas tips',
    drawLinks: 'Draw new links by dragging between POI and transit handles.',
    editPoi: 'Select a POI node, then edit its label from the sidebar.',
    export: 'Export',
    exportDescription: 'Temporarily fits the full graph into view before exporting the `.react-flow` canvas as SVG.',
    exportSvg: 'Export SVG',
    exportingSvg: 'Exporting SVG…',
    gtfsSource: 'GTFS source',
    interactiveWorkspace: 'Interactive schematic workspace',
    language: 'Language',
    loadedFeedNotice: 'Loaded {fileName} · {routes} routes · {trips} trips · {stops} stops · {hubs} hubs',
    loadFeedToBrowse: 'Load a feed to browse routes.',
    loadFeedToRestoreSharedMap: 'Shared map found. Upload the matching GTFS zip to restore the saved layout.',
    noFeedLoaded: 'No feed loaded yet.',
    noRoutesMatch: 'No routes match the current search.',
    nodeLabelsDescription: 'Canvas labels switch between RTL and LTR reading order without resetting node positions.',
    phase: 'Phase 6',
    poiDescription: 'Create a POI, click it on the canvas, then edit its label here.',
    poiNodes: 'POI nodes',
    realDataOnly: 'Real data only',
    resultLabel: '{count} route{plural} shown from the loaded GTFS feed',
    routeMetadata: 'Route metadata',
    searchAndSelection: 'Search & selection',
    searchPlaceholder: 'e.g. A1, Red Line, 480',
    searchRailLightBus: 'Search rail, light rail, or bus lines',
    selectPoiLabel: 'Selected POI label',
    shareCopied: 'Share link copied to clipboard.',
    shareCopyFailed: 'Unable to copy the share link. Copy it from the address bar instead.',
    shareDescription: 'Creates a compressed GitHub Pages-safe URL with the selected lines, POIs, and node positions.',
    shareMap: 'Share Map',
    trainNumberTemplate: 'Train number template',
    uploadGtfs: 'Upload an official Israel MOT GTFS zip archive',
    vectorSvg: 'SVG',
  },
  'עברית': {
    activeLanguage: 'שפה פעילה',
    addPoi: 'הוספת נקודת עניין למרכז הקנבס',
    architecture: 'ארכיטקטורה',
    canvasRegionDescription:
      'השתמשו בגרף האינטראקטיבי כדי לבדוק תחנות GTFS ומוקדי מעבר, להוסיף נקודות עניין מהסרגל הצדדי, לצייר חיבורים אוקטילינאריים באמצעות העכבר, ולייצא או לשתף את קנבס React Flow המלא.',
    canvasTips: 'טיפים לקנבס',
    drawLinks: 'צרו חיבורים חדשים על ידי גרירה בין ידיות של נקודות עניין ותחנות.',
    editPoi: 'בחרו נקודת עניין ואז ערכו את התווית שלה מהסרגל הצדדי.',
    export: 'ייצוא',
    exportDescription: 'הגרף כולו מותאם זמנית למסך לפני ייצוא קנבס `.react-flow` כ־SVG.',
    exportSvg: 'ייצוא SVG',
    exportingSvg: 'מייצא SVG…',
    gtfsSource: 'מקור GTFS',
    interactiveWorkspace: 'סביבת עבודה סכמטית אינטראקטיבית',
    language: 'שפה',
    loadedFeedNotice: 'נטען {fileName} · ‏{routes} קווים · ‏{trips} נסיעות · ‏{stops} תחנות · ‏{hubs} מוקדים',
    loadFeedToBrowse: 'טענו פיד כדי לעיין בקווים.',
    loadFeedToRestoreSharedMap: 'נמצאה מפה משותפת. העלו את קובץ ה‑GTFS המתאים כדי לשחזר את הפריסה השמורה.',
    noFeedLoaded: 'עדיין לא נטען פיד.',
    noRoutesMatch: 'אין קווים התואמים לחיפוש הנוכחי.',
    nodeLabelsDescription: 'תוויות הקנבס עוברות בין RTL ל‑LTR בלי לאפס את מיקומי הצמתים.',
    phase: 'שלב 6',
    poiDescription: 'צרו נקודת עניין, לחצו עליה בקנבס ואז ערכו את התווית כאן.',
    poiNodes: 'נקודות עניין',
    realDataOnly: 'נתונים אמיתיים בלבד',
    resultLabel: '{count} קווים מוצגים מתוך פיד ה‑GTFS שנטען',
    routeMetadata: 'פרטי קו',
    searchAndSelection: 'חיפוש ובחירה',
    searchPlaceholder: 'למשל A1, Red Line, 480',
    searchRailLightBus: 'חפשו קווי רכבת, רכבת קלה או אוטובוס',
    selectPoiLabel: 'תווית נקודת העניין שנבחרה',
    shareCopied: 'קישור השיתוף הועתק ללוח.',
    shareCopyFailed: 'לא ניתן להעתיק את קישור השיתוף. העתיקו אותו משורת הכתובת.',
    shareDescription: 'יוצר כתובת דחוסה ותואמת GitHub Pages עם הקווים, נקודות העניין ומיקומי הצמתים.',
    shareMap: 'שיתוף מפה',
    trainNumberTemplate: 'תבנית מספר רכבת',
    uploadGtfs: 'העלו קובץ ZIP רשמי של GTFS ממשרד התחבורה',
    vectorSvg: 'SVG',
  },
  'العربية': {
    activeLanguage: 'اللغة النشطة',
    addPoi: 'إضافة نقطة اهتمام إلى وسط اللوحة',
    architecture: 'البنية',
    canvasRegionDescription:
      'استخدم المخطط التفاعلي لفحص محطات GTFS وعُقد التحويل، وإضافة نقاط اهتمام من الشريط الجانبي، ورسم وصلات ثمانية الاتجاهات بالمؤشر، ثم تصدير أو مشاركة لوحة React Flow كاملة.',
    canvasTips: 'نصائح اللوحة',
    drawLinks: 'ارسم وصلات جديدة عبر السحب بين مقابض نقاط الاهتمام والمحطات.',
    editPoi: 'حدّد نقطة اهتمام ثم عدّل تسميتها من الشريط الجانبي.',
    export: 'تصدير',
    exportDescription: 'يتم احتواء المخطط كاملًا مؤقتًا قبل تصدير لوحة `.react-flow` كملف SVG.',
    exportSvg: 'تصدير SVG',
    exportingSvg: 'جارٍ تصدير SVG…',
    gtfsSource: 'مصدر GTFS',
    interactiveWorkspace: 'مساحة عمل تخطيطية تفاعلية',
    language: 'اللغة',
    loadedFeedNotice: 'تم تحميل {fileName} · {routes} خطوط · {trips} رحلات · {stops} محطات · {hubs} مراكز',
    loadFeedToBrowse: 'حمّل تغذية للتصفح بين الخطوط.',
    loadFeedToRestoreSharedMap: 'تم العثور على خريطة مشتركة. حمّل ملف GTFS المطابق لاستعادة التخطيط المحفوظ.',
    noFeedLoaded: 'لم يتم تحميل أي تغذية بعد.',
    noRoutesMatch: 'لا توجد خطوط تطابق البحث الحالي.',
    nodeLabelsDescription: 'تبدّل تسميات اللوحة بين اتجاهي RTL وLTR بدون إعادة تعيين مواقع العقد.',
    phase: 'المرحلة 6',
    poiDescription: 'أنشئ نقطة اهتمام، ثم اضغط عليها في اللوحة وعدّل تسميتها هنا.',
    poiNodes: 'نقاط الاهتمام',
    realDataOnly: 'بيانات حقيقية فقط',
    resultLabel: 'يتم عرض {count} خطوط من تغذية GTFS المحمّلة',
    routeMetadata: 'بيانات الخط',
    searchAndSelection: 'البحث والاختيار',
    searchPlaceholder: 'مثال: A1 أو Red Line أو 480',
    searchRailLightBus: 'ابحث عن خطوط القطار أو القطار الخفيف أو الحافلات',
    selectPoiLabel: 'تسمية نقطة الاهتمام المحددة',
    shareCopied: 'تم نسخ رابط المشاركة إلى الحافظة.',
    shareCopyFailed: 'تعذر نسخ رابط المشاركة. انسخه من شريط العنوان بدلًا من ذلك.',
    shareDescription: 'ينشئ رابطًا مضغوطًا وآمنًا مع GitHub Pages يتضمن الخطوط ونقاط الاهتمام ومواقع العقد.',
    shareMap: 'مشاركة الخريطة',
    trainNumberTemplate: 'قالب رقم القطار',
    uploadGtfs: 'حمّل ملف GTFS رسمي بصيغة ZIP من وزارة المواصلات',
    vectorSvg: 'SVG',
  },
} satisfies Record<TransitLanguage, Record<string, string>>
